production: false

# super user
super_username: supersu
super_password: mypasswordisstrong

# database
db_host: "127.0.0.1"
db_port: "5432"
db_name: blog
db_user: postgres
db_password: postgres

# app
app_name: Mize BLog
base_url: http://localhost:8080 #end without slash
base_url_v1: http://localhost:8080/v1 #end without slash
port: "8080"

# auth
secretkey: d09sa;'/!djosi8ds0a0das

# smtp
smtp_host: smtp.gmail.com
smtp_port: 587
smtp_sender: "Mize Team <devlufriraismaulana@gmail.com>"
smtp_email: devlufriraismaulana@gmail.com
smtp_password: Secret#1

# redis
redis_host: localhost
redis_port: "6379"
redis_password: redis
redis_db: 0
